In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [116]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue'],
    'size':['small','medium','large','medium','small','large'],
    'gender':['male','female','male','female','male','female'],
})

In [117]:
df.head()

color    size  gender
0    red   small    male
1   blue  medium  female
2  green   large    male
3  green  medium  female
4    red   small    male

In [118]:
encoder=OneHotEncoder()

In [119]:
encoded_color=encoder.fit_transform(df[["color"]]).toarray()
print(encoded_color)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [120]:
encoded_size=encoder.fit_transform(df[["size"]]).toarray()
print(encoded_size)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [121]:
df_encoded_size=pd.DataFrame(encoded_size,columns=encoder.get_feature_names_out())
print(df_encoded_size)

   size_large  size_medium  size_small
0         0.0          0.0         1.0
1         0.0          1.0         0.0
2         1.0          0.0         0.0
3         0.0          1.0         0.0
4         0.0          0.0         1.0
5         1.0          0.0         0.0


In [122]:
df_color=pd.DataFrame(encoded_color,columns=encoder.get_feature_names_out())
print(df_color)

   size_large  size_medium  size_small
0         0.0          0.0         1.0
1         1.0          0.0         0.0
2         0.0          1.0         0.0
3         0.0          1.0         0.0
4         0.0          0.0         1.0
5         1.0          0.0         0.0


In [ ]:
red_arr=encoder.transform([["red"]]).toarray()
blue_arr=encoder.transform([["blue"]]).toarray()
green_arr=encoder.transform([["green"]]).toarray()
print(f"transformed red : {red_arr}")
print(f"transformed blue : {blue_arr}")
print(f"transformed green : {green_arr}")

In [ ]:
print(df.head())

In [ ]:
df_encoded_color=pd.DataFrame(encoded_color,columns=encoder.get_feature_names_out())
print(df_encoded_color)

In [ ]:
df1=pd.concat([df,df_encoded_color,df_encoded_size],axis=1)
print(f"shape of the new dataset :{df1.shape}")
print(f"head of the dataset : {df1.head()}")

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
import seaborn as snb

In [ ]:
df=snb.load_dataset("tips")

In [ ]:
print(type(df))

In [ ]:
print(f"{df.columns}")

In [ ]:
print(f"{df.head()}")

In [ ]:
print(f"sex : {df['sex'].unique()}")
print(f"smoker : {df['smoker'].unique()}")
print(f"day : {df['day'].unique()}")
print(f"time : {df['time'].unique()}")

In [ ]:
print(df["sex"].value_counts())

In [ ]:
lb_encoder=LabelEncoder()

In [ ]:
df_sex_encoded=lb_encoder.fit_transform(df["sex"])
df_smoker_encoded=lb_encoder.fit_transform(df["smoker"])
df_day_encoded=lb_encoder.fit_transform(df["day"])
df_time_encoded=lb_encoder.fit_transform(df["time"])

In [ ]:
print(type(df_sex_encoded))

In [ ]:
df_sex_encoded=pd.DataFrame(df_sex_encoded,columns=["sex"])
df_smoker_encoded=pd.DataFrame(df_smoker_encoded,columns=["smoker"])
df_day_encoded=pd.DataFrame(df_day_encoded,columns=["day"])
df_time_encoded=pd.DataFrame(df_time_encoded,columns=["time"])

In [ ]:
df1=pd.concat([df_sex_encoded,df_smoker_encoded,df_day_encoded,df_time_encoded],axis=1)

In [ ]:
print(f"{df1.head()}")

In [ ]:
print(f"{df1.columns}")

In [ ]:
print(f"unique sex encoded : {df1['sex'].value_counts()}")
print(f"unique smoker encoded : {df1['smoker'].value_counts()}")
print(f"unique days encoded : {df1['day'].value_counts()}")
print(f"unique time encoded : {df1['time'].value_counts()}")

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
print("implementing ordinal encoder based on the rank of the values")

In [ ]:
df=pd.DataFrame({
    "education":["school","college","graduate","post_graduate"]
})

In [ ]:
print(df.head())

In [ ]:
encoder=OrdinalEncoder(categories=[["school","college","graduate","post_graduate"]])

In [ ]:
encoder.fit_transform(df[["education"]])

In [ ]:
transformed_school = encoder.transform([["school"]])
transformed_college = encoder.transform([["college"]])
transformed_graduate = encoder.transform([["graduate"]])
transformed_pg = encoder.transform([["post_graduate"]])

In [ ]:
print(f"school : {transformed_school}")
print(f"college : {transformed_college}")
print(f"graduate : {transformed_graduate}")
print(f"post graduate : {transformed_pg}")

In [ ]:
print(f"implementing target guided ordinal encoding\n")

In [ ]:
df=pd.DataFrame({
    "city""":["new_york","london","paris","tokyo","new_york","paris"],
    "price":[200,150,300,250,150,300]
})

In [ ]:
print(df.head())

In [ ]:
city_mean_price=df.groupby("city")["price"].mean()
print(city_mean_price)

In [ ]:
city_mean_price=city_mean_price.to_dict()
print(city_mean_price)

In [ ]:
df["city_encoded"]=df["city"].map(city_mean_price)

In [ ]:
print(df.head())

In [124]:
x=df["city"]
y=df["city_encoded"]
print([x,y])

KeyError: 'city'