In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [31]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue'],
    'size':['small','medium','large','medium','small','large'],
    'gender':['male','female','male','female','male','female'],
})

In [32]:
df.head()

color    size  gender
0    red   small    male
1   blue  medium  female
2  green   large    male
3  green  medium  female
4    red   small    male

In [33]:
encoder=OneHotEncoder()

In [51]:
encoded_color=encoder.fit_transform(df[["color"]]).toarray()
print(encoded_color)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [35]:
encoded_size=encoder.fit_transform(df[["size"]]).toarray()
print(encoded_size)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [50]:
df_encoded_size=pd.DataFrame(encoded_size,columns=encoder.get_feature_names_out())
print(df_encoded_size)

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0


In [38]:
df_color=pd.DataFrame(encoded_color,columns=encoder.get_feature_names_out())
print(df_color)

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0


In [54]:
red_arr=encoder.transform([["red"]]).toarray()
blue_arr=encoder.transform([["blue"]]).toarray()
green_arr=encoder.transform([["green"]]).toarray()
print(f"transformed red : {red_arr}")
print(f"transformed blue : {blue_arr}")
print(f"transformed green : {green_arr}")

transformed red : [[0. 0. 1.]]
transformed blue : [[1. 0. 0.]]
transformed green : [[0. 1. 0.]]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [43]:
print(df.head())

   color    size  gender
0    red   small    male
1   blue  medium  female
2  green   large    male
3  green  medium  female
4    red   small    male


In [52]:
df_encoded_color=pd.DataFrame(encoded_color,columns=encoder.get_feature_names_out())
print(df_encoded_color)

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0


In [53]:
df1=pd.concat([df,df_encoded_color,df_encoded_size],axis=1)
print(f"shape of the new dataset :{df1.shape}")
print(f"head of the dataset : {df1.head()}")

shape of the new dataset :(6, 9)
head of the dataset :    color    size  gender  color_blue  color_green  color_red  color_blue  \
0    red   small    male         0.0          0.0        1.0         0.0   
1   blue  medium  female         1.0          0.0        0.0         0.0   
2  green   large    male         0.0          1.0        0.0         1.0   
3  green  medium  female         0.0          1.0        0.0         0.0   
4    red   small    male         0.0          0.0        1.0         0.0   

   color_green  color_red  
0          0.0        1.0  
1          1.0        0.0  
2          0.0        0.0  
3          1.0        0.0  
4          0.0        1.0  
